baseURL = "https://struggling-engineer.com/"
languageCode = "ja"
title = "ykitaaa's tech blog"
#theme = "PaperModX"
theme = "DoIt"
defaultContentLanguage = "ja"
hasCJKLanguage = true
summaryLength = 100
buildDrafts = false

[params]
showToc = true
TocOpen = true
TocSide = "left"
ShowReadingTime = true