baseURL = "https://struggling-engineer.com/"
languageCode = "ja"
title = "ykitaaa's tech blog"
theme = "PaperModX"
defaultContentLanguage = 'ja'

[params]
showToc = true
TocOpen = true
TocSide = 'left'
ShowReadingTime = true
summaryLength = 100
buildDrafts = false