baseURL = "https://struggling-engineer.com/"
#languageCode = "ja"
hasCJKLanguage = true
title = "ykitaaa's tech blog"
theme = "PaperModX"
defaultContentLanguage = "ja"
#summaryLength = 100
buildDrafts = false

[params]
showToc = true
TocOpen = true
TocSide = "left"
ShowReadingTime = true
