baseURL: "https://struggling-engineer.com/"
languageCode: "ja-jp"
title: "ykitaaa's tech blog"
theme: "PaperModX"

params:
  ShowToc: true
  TocOpen: true
  TocSide: 'left'

outputs:
  blogdown::html_page:
      toc: true